/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diagnostic;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import diagnostic.Enums.Categoria;
import diagnostic.Enums.Destinos;

/**
 *
 * @author Usuario
 */
public class frmRegistroAlumno extends javax.swing.JFrame {

    protected frmMenu ventana2;
    Viaje[] alumnosStack;

    /**
     * Creates new form frmVentana
     *
     * @param ventana2
     */
    public frmRegistroAlumno(frmMenu ventana2) {
        this.ventana2 = ventana2;
        initComponents();
        jComboBox1.setSelectedIndex(-1);
        alumnosStack = ventana2.alumnosStack;
        btnAgregar.setCursor(getCursor());
    }
    public frmRegistroAlumno(frmMenu ventana2, Viaje viaje) {
        this.ventana2 = ventana2;
        initComponents();
        jtfFolio.setEnabled(false);
        jtfFolio.setText(viaje.getFolio()+"");
        jList1.setEnabled(false);
        jList1.setSelectedIndex(viaje.getDestino().ordinal());
        jComboBox1.setEnabled(false);
        jComboBox1.setSelectedIndex(viaje.getCategoria().ordinal());
        jcbDiscount.setEnabled(false);
        jcbDiscount.setSelected(viaje.isDiscounted());
        btnAgregar.setVisible(false);
        btnEliminar.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbDiscount = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(diagnostic.Enums.Destinos.values());
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registro de Viajes");

        jLabel1.setText("Folio");

        jtfFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFolioActionPerformed(evt);
            }
        });
        jtfFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFolioKeyTyped(evt);
            }
        });

        jLabel2.setText("Destino");

        jcbDiscount.setText("Descuento");
        jcbDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDiscountActionPerformed(evt);
            }
        });

        jLabel6.setText("Cuenta con descuento?");

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jList1.setModel(new DefaultListModel<diagnostic.Enums.Destinos>() {{
            for (diagnostic.Enums.Destinos destino : diagnostic.Enums.Destinos.values()) {
                addElement(destino);
            }
        }});
        jScrollPane2.setViewportView(jList1);

        jLabel8.setText("Categoria");

        jComboBox1.setModel(new DefaultComboBoxModel<diagnostic.Enums.Categoria>() {{
            for (diagnostic.Enums.Categoria habitacion : diagnostic.Enums.Categoria.values()) {
                addElement(habitacion);
            }
        }});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfFolio)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar)
                                .addGap(40, 40, 40)
                                .addComponent(btnRegresar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jcbDiscount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:

        int dias;
        Destinos destino; //lista
        Categoria tipoHabitacion; //lista
        boolean isMonthlyPaid;

        try {
            isMonthlyPaid = jcbDiscount.isSelected();
            dias = Integer.parseInt(jtfFolio.getText());
            if (jList1.getSelectedValue() == null || jComboBox1.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "No puedes dejar vacio los campos");
                return;
            }
            destino = jList1.getSelectedValue();
            tipoHabitacion = ((Categoria) jComboBox1.getSelectedItem());
            alumnosStack[ventana2.count] = (new Viaje(dias, destino, tipoHabitacion, isMonthlyPaid));
            ventana2.count++;
            limpiar();
            JOptionPane.showMessageDialog(this, "Alumno agregado correctamente");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en el formato numerico");
        }

    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtfFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFolioActionPerformed

    private void jcbDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDiscountActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String user = JOptionPane.showInputDialog(this, "Ingresa el Folio del viaje a eliminar");
        if(user==null)
            return;
        for (int i = 0; i < ventana2.alumnosStack.length; i++) {
            if (ventana2.alumnosStack[i] != null && ("" + ventana2.alumnosStack[i].getFolio()).equals(user)) {
                for (int j = i; j < ventana2.alumnosStack.length - 1; j++) {
                    ventana2.alumnosStack[j] = ventana2.alumnosStack[j + 1]; 
                }
                ventana2.alumnosStack[ventana2.alumnosStack.length - 1] = null;
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Viaje con el folio " + user + " No encontrado");

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtfFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFolioKeyTyped
        // TODO add your handling code here:
        allowOnlyNumbers(evt);
    }//GEN-LAST:event_jtfFolioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmRegistroAlumno(new frmMenu()).setVisible(true);
        });
    }

    @Override
    public final Cursor getCursor() {
        return Toolkit.getDefaultToolkit().createCustomCursor(
                new ImageIcon("src/diagnostic/assets/add.png").getImage(), new Point(15, 15), "Custom  Cursor");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<diagnostic.Enums.Categoria> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<diagnostic.Enums.Destinos> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jcbDiscount;
    private javax.swing.JTextField jtfFolio;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jtfFolio.setText("");
        jList1.clearSelection();
        jComboBox1.setSelectedIndex(-1);
        jcbDiscount.setSelected(false);
    }

    private void allowOnlyNumbers(KeyEvent evt) {
        char keyChar = evt.getKeyChar();
        if (!Character.isDigit(keyChar) && keyChar != KeyEvent.VK_BACK_SPACE && keyChar != KeyEvent.VK_DELETE) {
            evt.consume(); // Ignore the key event if it's not a digit or allowed key
        }
    }
}
